name: Bugreport
description: Melde einen Fehler
labels: [Ungeklärter Bug]
body:
  - type: input
    attributes:
      label: Beschreibung
      description: Eine einfache Beschreibung des Fehlers
    validations:
      required: true

  - type: input
    attributes:
      label: Wobei ist der Fehler aufgetreten?
      description: Dies kann zum Beispiel ein Command sein
    validations:
      required: true

  - type: input
    attributes:
      label: Wann / Wo ist der Fehler aufgetreten?
      description: Am besten wäre hier ein Nachrichtenlink zum Command / zur Nachricht oder ein Datum
    validations:
      required: true

  - type: textarea
    attributes:
      label: Erwartetes Verhalten
      description: Was hätte normalerweise passieren sollen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Tatsächliches Verhalten
      description: Was ist stattdessen passiert?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: Ich habe nach bereits vorhandenen Fehlermeldungen über diesen Fehler gesucht.
          required: true
        - label: Ich habe alle mir bekannten Informationen weitergegeben.
          required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
